
// This file is automatically generated.
// Do not directly edit.
// Generated on 2020-08-05T03:11:22.788Z

// Version 1.0.0

namespace Camille.Lcu
{
    public static class LcuExtensions
    {
        public static LolChampSelectEndpoints LolChampSelect(this ILcu @base)
        {
            return new LolChampSelectEndpoints(@base);
        }

        public static LolLoginEndpoints LolLogin(this ILcu @base)
        {
            return new LolLoginEndpoints(@base);
        }

        public static LolRankedEndpoints LolRanked(this ILcu @base)
        {
            return new LolRankedEndpoints(@base);
        }

        public static LolSummonerEndpoints LolSummoner(this ILcu @base)
        {
            return new LolSummonerEndpoints(@base);
        }

        public static RiotClientEndpoints RiotClient(this ILcu @base)
        {
            return new RiotClientEndpoints(@base);
        }

    }
}

