
// This file is automatically generated.
// Do not directly edit.
// Generated on 2021-07-24T03:22:52.080Z

using System;
using System.ComponentModel.DataAnnotations;

namespace Camille.Enums
{
    /// <summary>
    /// Maps enum based on maps.json.
    /// </summary>
    public enum Map
    {
        [Obsolete]
        [Display(Name = "Summoner's Rift", Description = "Summoner's Rift\nOriginal Summer variant")]
        SUMMONERS_RIFT_ORIGINAL_SUMMER_VARIANT = 1,

        [Obsolete]
        [Display(Name = "Summoner's Rift", Description = "Summoner's Rift\nOriginal Autumn variant")]
        SUMMONERS_RIFT_ORIGINAL_AUTUMN_VARIANT = 2,

        [Display(Name = "The Proving Grounds", Description = "The Proving Grounds\nTutorial Map")]
        THE_PROVING_GROUNDS = 3,

        [Obsolete]
        [Display(Name = "Twisted Treeline", Description = "Twisted Treeline\nOriginal Version")]
        TWISTED_TREELINE_ORIGINAL_VERSION = 4,

        [Display(Name = "The Crystal Scar", Description = "The Crystal Scar\nDominion map")]
        THE_CRYSTAL_SCAR = 8,

        [Display(Name = "Twisted Treeline", Description = "Twisted Treeline\nLast TT map")]
        TWISTED_TREELINE = 10,

        [Display(Name = "Summoner's Rift", Description = "Summoner's Rift\nCurrent Version")]
        SUMMONERS_RIFT = 11,

        [Display(Name = "Howling Abyss", Description = "Howling Abyss\nARAM map")]
        HOWLING_ABYSS = 12,

        [Display(Name = "Butcher's Bridge", Description = "Butcher's Bridge\nAlternate ARAM map")]
        BUTCHERS_BRIDGE = 14,

        [Display(Name = "Cosmic Ruins", Description = "Cosmic Ruins\nDark Star: Singularity map")]
        COSMIC_RUINS = 16,

        [Display(Name = "Valoran City Park", Description = "Valoran City Park\nStar Guardian Invasion map")]
        VALORAN_CITY_PARK = 18,

        [Display(Name = "Substructure 43", Description = "Substructure 43\nPROJECT: Hunters map")]
        SUBSTRUCTURE_43 = 19,

        [Display(Name = "Crash Site", Description = "Crash Site\nOdyssey: Extraction map")]
        CRASH_SITE = 20,

        [Display(Name = "Nexus Blitz", Description = "Nexus Blitz\nNexus Blitz map")]
        NEXUS_BLITZ = 21,

        [Display(Name = "Convergence", Description = "Convergence\nTeamfight Tactics map")]
        CONVERGENCE = 22,

    }
}
