
// This file is automatically generated.
// Do not directly edit.
// Generated on 2020-07-17T03:12:02.501Z

using System.ComponentModel.DataAnnotations;

namespace Camille.Enums
{
    /// <summary>
    /// Seasons enum based on Seasons.json.
    /// </summary>
#if USE_SYSTEXTJSON
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
#endif
    public enum Season
    {
        [Display(Name = "SEASON 3")]
        SEASON_3 = 1,
        [Display(Name = "PRESEASON 2014")]
        PRESEASON_2014 = 2,
        [Display(Name = "SEASON 2014")]
        SEASON_2014 = 3,
        [Display(Name = "PRESEASON 2015")]
        PRESEASON_2015 = 4,
        [Display(Name = "SEASON 2015")]
        SEASON_2015 = 5,
        [Display(Name = "PRESEASON 2016")]
        PRESEASON_2016 = 6,
        [Display(Name = "SEASON 2016")]
        SEASON_2016 = 7,
        [Display(Name = "PRESEASON 2017")]
        PRESEASON_2017 = 8,
        [Display(Name = "SEASON 2017")]
        SEASON_2017 = 9,
        [Display(Name = "PRESEASON 2018")]
        PRESEASON_2018 = 10,
        [Display(Name = "SEASON 2018")]
        SEASON_2018 = 11,
        [Display(Name = "PRESEASON 2019")]
        PRESEASON_2019 = 12,
        [Display(Name = "SEASON 2019")]
        SEASON_2019 = 13,
    }
}
