
﻿
// This file is automatically generated.
// Do not directly edit.
// Generated on 2021-10-24T18:42:52.916Z

// http://www.mingweisamuel.com/lolgameapi-schema/tool/


using System.Collections.Generic;
using System.Linq;


#if USE_NEWTONSOFT
using JsonPropertyAttribute = Newtonsoft.Json.JsonPropertyAttribute;
using JsonExtensionDataAttribute = Newtonsoft.Json.JsonExtensionDataAttribute;
#elif USE_SYSTEXTJSON
using JsonPropertyAttribute = System.Text.Json.Serialization.JsonPropertyNameAttribute;
using JsonExtensionDataAttribute = System.Text.Json.Serialization.JsonExtensionDataAttribute;
#else
#error One of USE_NEWTONSOFT or USE_SYSTEXTJSON must be set.
#endif

// ReSharper disable InconsistentNaming

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// AllGameData data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class AllGameData
    {

#nullable disable
        public AllGameData() {}
#nullable restore

        [JsonProperty("activePlayer")]
        public ActivePlayer ActivePlayer { get; set; }
        [JsonProperty("allPlayers")]
        public Player[] AllPlayers { get; set; }
        [JsonProperty("events")]
        public EventData Events { get; set; }
        [JsonProperty("gameData")]
        public GameStats GameData { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "AllGameData("
                + "ActivePlayer: " + ActivePlayer + ", "
                + "AllPlayers: " + AllPlayers + ", "
                + "Events: " + Events + ", "
                + "GameData: " + GameData + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// Ability data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class Ability
    {

#nullable disable
        public Ability() {}
#nullable restore

        [JsonProperty("abilityLevel")]
        public int AbilityLevel { get; set; }
        [JsonProperty("displayName")]
        public string DisplayName { get; set; }
        [JsonProperty("id")]
        public string Id { get; set; }
        [JsonProperty("rawDescription")]
        public string RawDescription { get; set; }
        [JsonProperty("rawDisplayName")]
        public string RawDisplayName { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "Ability("
                + "AbilityLevel: " + AbilityLevel + ", "
                + "DisplayName: " + DisplayName + ", "
                + "Id: " + Id + ", "
                + "RawDescription: " + RawDescription + ", "
                + "RawDisplayName: " + RawDisplayName + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// Passive data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class Passive
    {

#nullable disable
        public Passive() {}
#nullable restore

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }
        [JsonProperty("id")]
        public string Id { get; set; }
        [JsonProperty("rawDescription")]
        public string RawDescription { get; set; }
        [JsonProperty("rawDisplayName")]
        public string RawDisplayName { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "Passive("
                + "DisplayName: " + DisplayName + ", "
                + "Id: " + Id + ", "
                + "RawDescription: " + RawDescription + ", "
                + "RawDisplayName: " + RawDisplayName + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// ActivePlayerAbilities data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class ActivePlayerAbilities
    {

#nullable disable
        public ActivePlayerAbilities() {}
#nullable restore

        [JsonProperty("E")]
        public Ability E { get; set; }
        [JsonProperty("Passive")]
        public Passive Passive { get; set; }
        [JsonProperty("Q")]
        public Ability Q { get; set; }
        [JsonProperty("R")]
        public Ability R { get; set; }
        [JsonProperty("W")]
        public Ability W { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "ActivePlayerAbilities("
                + "E: " + E + ", "
                + "Passive: " + Passive + ", "
                + "Q: " + Q + ", "
                + "R: " + R + ", "
                + "W: " + W + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// PlayerChampionStats data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class PlayerChampionStats
    {

#nullable disable
        public PlayerChampionStats() {}
#nullable restore

        [JsonProperty("abilityHaste")]
        public double AbilityHaste { get; set; }
        [JsonProperty("abilityPower")]
        public double AbilityPower { get; set; }
        [JsonProperty("armor")]
        public double Armor { get; set; }
        [JsonProperty("armorPenetrationFlat")]
        public double ArmorPenetrationFlat { get; set; }
        [JsonProperty("armorPenetrationPercent")]
        public double ArmorPenetrationPercent { get; set; }
        [JsonProperty("attackDamage")]
        public double AttackDamage { get; set; }
        [JsonProperty("attackRange")]
        public double AttackRange { get; set; }
        [JsonProperty("attackSpeed")]
        public double AttackSpeed { get; set; }
        [JsonProperty("bonusArmorPenetrationPercent")]
        public double BonusArmorPenetrationPercent { get; set; }
        [JsonProperty("bonusMagicPenetrationPercent")]
        public double BonusMagicPenetrationPercent { get; set; }
        [JsonProperty("critChance")]
        public double CritChance { get; set; }
        [JsonProperty("critDamage")]
        public double CritDamage { get; set; }
        [JsonProperty("currentHealth")]
        public double CurrentHealth { get; set; }
        [JsonProperty("healShieldPower")]
        public double HealShieldPower { get; set; }
        [JsonProperty("healthRegenRate")]
        public double HealthRegenRate { get; set; }
        [JsonProperty("lifeSteal")]
        public double LifeSteal { get; set; }
        [JsonProperty("magicLethality")]
        public double MagicLethality { get; set; }
        [JsonProperty("magicPenetrationFlat")]
        public double MagicPenetrationFlat { get; set; }
        [JsonProperty("magicPenetrationPercent")]
        public double MagicPenetrationPercent { get; set; }
        [JsonProperty("magicResist")]
        public double MagicResist { get; set; }
        [JsonProperty("maxHealth")]
        public double MaxHealth { get; set; }
        [JsonProperty("moveSpeed")]
        public double MoveSpeed { get; set; }
        [JsonProperty("omnivamp")]
        public double Omnivamp { get; set; }
        [JsonProperty("physicalLethality")]
        public double PhysicalLethality { get; set; }
        [JsonProperty("physicalVamp")]
        public double PhysicalVamp { get; set; }
        [JsonProperty("resourceMax")]
        public double ResourceMax { get; set; }
        [JsonProperty("resourceRegenRate")]
        public double ResourceRegenRate { get; set; }
        [JsonProperty("resourceType")]
        public string ResourceType { get; set; }
        [JsonProperty("resourceValue")]
        public double ResourceValue { get; set; }
        [JsonProperty("spellVamp")]
        public double SpellVamp { get; set; }
        [JsonProperty("tenacity")]
        public double Tenacity { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "PlayerChampionStats("
                + "AbilityHaste: " + AbilityHaste + ", "
                + "AbilityPower: " + AbilityPower + ", "
                + "Armor: " + Armor + ", "
                + "ArmorPenetrationFlat: " + ArmorPenetrationFlat + ", "
                + "ArmorPenetrationPercent: " + ArmorPenetrationPercent + ", "
                + "AttackDamage: " + AttackDamage + ", "
                + "AttackRange: " + AttackRange + ", "
                + "AttackSpeed: " + AttackSpeed + ", "
                + "BonusArmorPenetrationPercent: " + BonusArmorPenetrationPercent + ", "
                + "BonusMagicPenetrationPercent: " + BonusMagicPenetrationPercent + ", "
                + "CritChance: " + CritChance + ", "
                + "CritDamage: " + CritDamage + ", "
                + "CurrentHealth: " + CurrentHealth + ", "
                + "HealShieldPower: " + HealShieldPower + ", "
                + "HealthRegenRate: " + HealthRegenRate + ", "
                + "LifeSteal: " + LifeSteal + ", "
                + "MagicLethality: " + MagicLethality + ", "
                + "MagicPenetrationFlat: " + MagicPenetrationFlat + ", "
                + "MagicPenetrationPercent: " + MagicPenetrationPercent + ", "
                + "MagicResist: " + MagicResist + ", "
                + "MaxHealth: " + MaxHealth + ", "
                + "MoveSpeed: " + MoveSpeed + ", "
                + "Omnivamp: " + Omnivamp + ", "
                + "PhysicalLethality: " + PhysicalLethality + ", "
                + "PhysicalVamp: " + PhysicalVamp + ", "
                + "ResourceMax: " + ResourceMax + ", "
                + "ResourceRegenRate: " + ResourceRegenRate + ", "
                + "ResourceType: " + ResourceType + ", "
                + "ResourceValue: " + ResourceValue + ", "
                + "SpellVamp: " + SpellVamp + ", "
                + "Tenacity: " + Tenacity + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// GeneralRune data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class GeneralRune
    {

#nullable disable
        public GeneralRune() {}
#nullable restore

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }
        [JsonProperty("id")]
        public int Id { get; set; }
        [JsonProperty("rawDescription")]
        public string RawDescription { get; set; }
        [JsonProperty("rawDisplayName")]
        public string RawDisplayName { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "GeneralRune("
                + "DisplayName: " + DisplayName + ", "
                + "Id: " + Id + ", "
                + "RawDescription: " + RawDescription + ", "
                + "RawDisplayName: " + RawDisplayName + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// StatRune data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class StatRune
    {

#nullable disable
        public StatRune() {}
#nullable restore

        [JsonProperty("id")]
        public int Id { get; set; }
        [JsonProperty("rawDescription")]
        public string RawDescription { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "StatRune("
                + "Id: " + Id + ", "
                + "RawDescription: " + RawDescription + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// ActivePlayerRunes data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class ActivePlayerRunes
    {

#nullable disable
        public ActivePlayerRunes() {}
#nullable restore

        [JsonProperty("generalRunes")]
        public GeneralRune[] GeneralRunes { get; set; }
        [JsonProperty("keystone")]
        public GeneralRune Keystone { get; set; }
        [JsonProperty("primaryRuneTree")]
        public GeneralRune PrimaryRuneTree { get; set; }
        [JsonProperty("secondaryRuneTree")]
        public GeneralRune SecondaryRuneTree { get; set; }
        [JsonProperty("statRunes")]
        public StatRune[] StatRunes { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "ActivePlayerRunes("
                + "GeneralRunes: " + GeneralRunes + ", "
                + "Keystone: " + Keystone + ", "
                + "PrimaryRuneTree: " + PrimaryRuneTree + ", "
                + "SecondaryRuneTree: " + SecondaryRuneTree + ", "
                + "StatRunes: " + StatRunes + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// ActivePlayer data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class ActivePlayer
    {

#nullable disable
        public ActivePlayer() {}
#nullable restore

        [JsonProperty("abilities")]
        public ActivePlayerAbilities? Abilities { get; set; }
        [JsonProperty("championStats")]
        public PlayerChampionStats? ChampionStats { get; set; }
        [JsonProperty("currentGold")]
        public double? CurrentGold { get; set; }
        [JsonProperty("error")]
        public string? Error { get; set; }
        [JsonProperty("fullRunes")]
        public ActivePlayerRunes? FullRunes { get; set; }
        [JsonProperty("level")]
        public int? Level { get; set; }
        [JsonProperty("summonerName")]
        public string? SummonerName { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "ActivePlayer("
                + "Abilities: " + Abilities + ", "
                + "ChampionStats: " + ChampionStats + ", "
                + "CurrentGold: " + CurrentGold + ", "
                + "FullRunes: " + FullRunes + ", "
                + "Level: " + Level + ", "
                + "SummonerName: " + SummonerName + ", "
                + "Error: " + Error + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// PlayerItem data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class PlayerItem
    {

#nullable disable
        public PlayerItem() {}
#nullable restore

        [JsonProperty("canUse")]
        public bool CanUse { get; set; }
        [JsonProperty("consumable")]
        public bool Consumable { get; set; }
        [JsonProperty("count")]
        public int Count { get; set; }
        [JsonProperty("displayName")]
        public string DisplayName { get; set; }
        [JsonProperty("itemID")]
        public int ItemID { get; set; }
        [JsonProperty("price")]
        public int Price { get; set; }
        [JsonProperty("rawDescription")]
        public string RawDescription { get; set; }
        [JsonProperty("rawDisplayName")]
        public string RawDisplayName { get; set; }
        [JsonProperty("slot")]
        public int Slot { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "PlayerItem("
                + "CanUse: " + CanUse + ", "
                + "Consumable: " + Consumable + ", "
                + "Count: " + Count + ", "
                + "DisplayName: " + DisplayName + ", "
                + "ItemID: " + ItemID + ", "
                + "Price: " + Price + ", "
                + "RawDescription: " + RawDescription + ", "
                + "RawDisplayName: " + RawDisplayName + ", "
                + "Slot: " + Slot + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// PlayerRunes data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class PlayerRunes
    {

#nullable disable
        public PlayerRunes() {}
#nullable restore

        [JsonProperty("keystone")]
        public GeneralRune Keystone { get; set; }
        [JsonProperty("primaryRuneTree")]
        public GeneralRune PrimaryRuneTree { get; set; }
        [JsonProperty("secondaryRuneTree")]
        public GeneralRune SecondaryRuneTree { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "PlayerRunes("
                + "Keystone: " + Keystone + ", "
                + "PrimaryRuneTree: " + PrimaryRuneTree + ", "
                + "SecondaryRuneTree: " + SecondaryRuneTree + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// PlayerScores data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class PlayerScores
    {

#nullable disable
        public PlayerScores() {}
#nullable restore

        [JsonProperty("assists")]
        public int Assists { get; set; }
        [JsonProperty("creepScore")]
        public int CreepScore { get; set; }
        [JsonProperty("deaths")]
        public int Deaths { get; set; }
        [JsonProperty("kills")]
        public int Kills { get; set; }
        [JsonProperty("wardScore")]
        public double WardScore { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "PlayerScores("
                + "Assists: " + Assists + ", "
                + "CreepScore: " + CreepScore + ", "
                + "Deaths: " + Deaths + ", "
                + "Kills: " + Kills + ", "
                + "WardScore: " + WardScore + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// PlayerSummonerSpell data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class PlayerSummonerSpell
    {

#nullable disable
        public PlayerSummonerSpell() {}
#nullable restore

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }
        [JsonProperty("rawDescription")]
        public string RawDescription { get; set; }
        [JsonProperty("rawDisplayName")]
        public string RawDisplayName { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "PlayerSummonerSpell("
                + "DisplayName: " + DisplayName + ", "
                + "RawDescription: " + RawDescription + ", "
                + "RawDisplayName: " + RawDisplayName + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// PlayerSummonerSpells data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class PlayerSummonerSpells
    {

#nullable disable
        public PlayerSummonerSpells() {}
#nullable restore

        [JsonProperty("summonerSpellOne")]
        public PlayerSummonerSpell SummonerSpellOne { get; set; }
        [JsonProperty("summonerSpellTwo")]
        public PlayerSummonerSpell SummonerSpellTwo { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "PlayerSummonerSpells("
                + "SummonerSpellOne: " + SummonerSpellOne + ", "
                + "SummonerSpellTwo: " + SummonerSpellTwo + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// Player data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class Player
    {

#nullable disable
        public Player() {}
#nullable restore

        [JsonProperty("championName")]
        public string ChampionName { get; set; }
        [JsonProperty("isBot")]
        public bool IsBot { get; set; }
        [JsonProperty("isDead")]
        public bool IsDead { get; set; }
        [JsonProperty("items")]
        public PlayerItem[] Items { get; set; }
        [JsonProperty("level")]
        public int Level { get; set; }
        [JsonProperty("position")]
        public string Position { get; set; }
        [JsonProperty("rawChampionName")]
        public string RawChampionName { get; set; }
        [JsonProperty("rawSkinName")]
        public string? RawSkinName { get; set; }
        [JsonProperty("respawnTimer")]
        public double RespawnTimer { get; set; }
        [JsonProperty("runes")]
        public PlayerRunes Runes { get; set; }
        [JsonProperty("scores")]
        public PlayerScores Scores { get; set; }
        [JsonProperty("skinID")]
        public int SkinID { get; set; }
        [JsonProperty("skinName")]
        public string? SkinName { get; set; }
        [JsonProperty("summonerName")]
        public string SummonerName { get; set; }
        [JsonProperty("summonerSpells")]
        public PlayerSummonerSpells SummonerSpells { get; set; }
        [JsonProperty("team")]
        public string Team { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "Player("
                + "ChampionName: " + ChampionName + ", "
                + "IsBot: " + IsBot + ", "
                + "IsDead: " + IsDead + ", "
                + "Items: " + Items + ", "
                + "Level: " + Level + ", "
                + "Position: " + Position + ", "
                + "RawChampionName: " + RawChampionName + ", "
                + "RawSkinName: " + RawSkinName + ", "
                + "RespawnTimer: " + RespawnTimer + ", "
                + "Runes: " + Runes + ", "
                + "Scores: " + Scores + ", "
                + "SkinID: " + SkinID + ", "
                + "SkinName: " + SkinName + ", "
                + "SummonerName: " + SummonerName + ", "
                + "SummonerSpells: " + SummonerSpells + ", "
                + "Team: " + Team + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// Event data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class Event
    {

#nullable disable
        public Event() {}
#nullable restore

        [JsonProperty("Acer")]
        public string? Acer { get; set; }
        [JsonProperty("AcingTeam")]
        public string? AcingTeam { get; set; }
        [JsonProperty("Assisters")]
        public string[]? Assisters { get; set; }
        [JsonProperty("DragonType")]
        public string? DragonType { get; set; }
        [JsonProperty("EventID")]
        public int EventID { get; set; }
        [JsonProperty("EventName")]
        public string EventName { get; set; }
        [JsonProperty("EventTime")]
        public double EventTime { get; set; }
        [JsonProperty("InhibKilled")]
        public string? InhibKilled { get; set; }
        [JsonProperty("InhibRespawned")]
        public string? InhibRespawned { get; set; }
        [JsonProperty("InhibRespawningSoon")]
        public string? InhibRespawningSoon { get; set; }
        [JsonProperty("KillerName")]
        public string? KillerName { get; set; }
        [JsonProperty("KillStreak")]
        public int? KillStreak { get; set; }
        [JsonProperty("Recipient")]
        public string? Recipient { get; set; }
        [JsonProperty("Result")]
        public string? Result { get; set; }
        [JsonProperty("Stolen")]
        public string? Stolen { get; set; }
        [JsonProperty("TurretKilled")]
        public string? TurretKilled { get; set; }
        [JsonProperty("VictimName")]
        public string? VictimName { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "Event("
                + "EventID: " + EventID + ", "
                + "EventName: " + EventName + ", "
                + "EventTime: " + EventTime + ", "
                + "Assisters: " + Assisters + ", "
                + "KillerName: " + KillerName + ", "
                + "VictimName: " + VictimName + ", "
                + "Recipient: " + Recipient + ", "
                + "Acer: " + Acer + ", "
                + "AcingTeam: " + AcingTeam + ", "
                + "DragonType: " + DragonType + ", "
                + "Stolen: " + Stolen + ", "
                + "TurretKilled: " + TurretKilled + ", "
                + "InhibKilled: " + InhibKilled + ", "
                + "InhibRespawningSoon: " + InhibRespawningSoon + ", "
                + "InhibRespawned: " + InhibRespawned + ", "
                + "Result: " + Result + ", "
                + "KillStreak: " + KillStreak + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// EventData data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class EventData
    {

#nullable disable
        public EventData() {}
#nullable restore

        [JsonProperty("Events")]
        public Event[] Events { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "EventData("
                + "Events: " + Events + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}

namespace Camille.LolGame.LiveClientData
{
    /// <summary>
    /// GameStats data object. This class is automatically generated.<para />
    /// 
    /// </summary>
    public class GameStats
    {

#nullable disable
        public GameStats() {}
#nullable restore

        [JsonProperty("gameMode")]
        public string GameMode { get; set; }
        [JsonProperty("gameTime")]
        public double GameTime { get; set; }
        [JsonProperty("mapName")]
        public string MapName { get; set; }
        [JsonProperty("mapNumber")]
        public int MapNumber { get; set; }
        [JsonProperty("mapTerrain")]
        public string MapTerrain { get; set; }

        /// <summary>Contains any extra JSON properties that did not map to fields.</summary>
        [JsonExtensionData]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles")]
        public Dictionary<string, object> _AdditionalProperties { get; set; } = new Dictionary<string, object>();

        public override string ToString()
        {
            return "GameStats("
                + "GameMode: " + GameMode + ", "
                + "GameTime: " + GameTime + ", "
                + "MapName: " + MapName + ", "
                + "MapNumber: " + MapNumber + ", "
                + "MapTerrain: " + MapTerrain + ", "
                + "_AdditionalProperties: {" + string.Join(", ", _AdditionalProperties.Select(kv => $"\"{kv.Key}\": {kv.Value}")) + "})";
        }
    }
}


