
// This file is automatically generated.
// Do not directly edit.
// Generated on 2021-10-02T17:54:37.218Z

// Version 1.0.0

namespace Camille.LolGame
{
    public static class LolGameExtensions
    {
        public static LiveClientDataEndpoints LiveClientData(this ILolGameApi @base)
        {
            return new LiveClientDataEndpoints(@base);
        }

    }
}

