
// This file is automatically generated.
// Do not directly edit.
// Generated on 2021-01-14T03:03:01.159Z

// Version 1.0.0

namespace Camille.LolGame
{
    public static class LolGameExtensions
    {
        public static LiveClientDataEndpoints LiveClientData(this ILolGameApi @base)
        {
            return new LiveClientDataEndpoints(@base);
        }

    }
}

