
// This file is automatically generated.
// Do not directly edit.
// Generated on 2020-04-15T03:10:31.695Z

// Version 64f3c82d132f12808d8eb8f483d1d2182386c432

namespace Camille.RiotApi
{
    public static class RiotApiExtensions
    {
        public static ChampionMasteryV4Endpoints ChampionMasteryV4(this IRiotApi @base)
        {
            return new ChampionMasteryV4Endpoints(@base);
        }

        public static ChampionV3Endpoints ChampionV3(this IRiotApi @base)
        {
            return new ChampionV3Endpoints(@base);
        }

        public static ClashV1Endpoints ClashV1(this IRiotApi @base)
        {
            return new ClashV1Endpoints(@base);
        }

        public static LeagueExpV4Endpoints LeagueExpV4(this IRiotApi @base)
        {
            return new LeagueExpV4Endpoints(@base);
        }

        public static LeagueV4Endpoints LeagueV4(this IRiotApi @base)
        {
            return new LeagueV4Endpoints(@base);
        }

        public static LolStatusV3Endpoints LolStatusV3(this IRiotApi @base)
        {
            return new LolStatusV3Endpoints(@base);
        }

        public static LorRankedV1Endpoints LorRankedV1(this IRiotApi @base)
        {
            return new LorRankedV1Endpoints(@base);
        }

        public static MatchV4Endpoints MatchV4(this IRiotApi @base)
        {
            return new MatchV4Endpoints(@base);
        }

        public static SpectatorV4Endpoints SpectatorV4(this IRiotApi @base)
        {
            return new SpectatorV4Endpoints(@base);
        }

        public static SummonerV4Endpoints SummonerV4(this IRiotApi @base)
        {
            return new SummonerV4Endpoints(@base);
        }

        public static TftLeagueV1Endpoints TftLeagueV1(this IRiotApi @base)
        {
            return new TftLeagueV1Endpoints(@base);
        }

        public static TftMatchV1Endpoints TftMatchV1(this IRiotApi @base)
        {
            return new TftMatchV1Endpoints(@base);
        }

        public static TftSummonerV1Endpoints TftSummonerV1(this IRiotApi @base)
        {
            return new TftSummonerV1Endpoints(@base);
        }

        public static ThirdPartyCodeV4Endpoints ThirdPartyCodeV4(this IRiotApi @base)
        {
            return new ThirdPartyCodeV4Endpoints(@base);
        }

        public static TournamentStubV4Endpoints TournamentStubV4(this IRiotApi @base)
        {
            return new TournamentStubV4Endpoints(@base);
        }

        public static TournamentV4Endpoints TournamentV4(this IRiotApi @base)
        {
            return new TournamentV4Endpoints(@base);
        }

    }
}

