
// This file is automatically generated.
// Do not directly edit.
// Generated on 2020-11-06T01:42:24.768Z

// Version d593d1ca0f203b80a7e431484f65455a8d9c08dc

namespace Camille.RiotGames
{
    public static class RiotGamesExtensions
    {
        public static AccountV1Endpoints AccountV1(this IRiotGamesApi @base)
        {
            return new AccountV1Endpoints(@base);
        }

        public static ChampionMasteryV4Endpoints ChampionMasteryV4(this IRiotGamesApi @base)
        {
            return new ChampionMasteryV4Endpoints(@base);
        }

        public static ChampionV3Endpoints ChampionV3(this IRiotGamesApi @base)
        {
            return new ChampionV3Endpoints(@base);
        }

        public static ClashV1Endpoints ClashV1(this IRiotGamesApi @base)
        {
            return new ClashV1Endpoints(@base);
        }

        public static LeagueExpV4Endpoints LeagueExpV4(this IRiotGamesApi @base)
        {
            return new LeagueExpV4Endpoints(@base);
        }

        public static LeagueV4Endpoints LeagueV4(this IRiotGamesApi @base)
        {
            return new LeagueV4Endpoints(@base);
        }

        public static LolStatusV3Endpoints LolStatusV3(this IRiotGamesApi @base)
        {
            return new LolStatusV3Endpoints(@base);
        }

        public static LorMatchV1Endpoints LorMatchV1(this IRiotGamesApi @base)
        {
            return new LorMatchV1Endpoints(@base);
        }

        public static LorRankedV1Endpoints LorRankedV1(this IRiotGamesApi @base)
        {
            return new LorRankedV1Endpoints(@base);
        }

        public static MatchV4Endpoints MatchV4(this IRiotGamesApi @base)
        {
            return new MatchV4Endpoints(@base);
        }

        public static SpectatorV4Endpoints SpectatorV4(this IRiotGamesApi @base)
        {
            return new SpectatorV4Endpoints(@base);
        }

        public static SummonerV4Endpoints SummonerV4(this IRiotGamesApi @base)
        {
            return new SummonerV4Endpoints(@base);
        }

        public static TftLeagueV1Endpoints TftLeagueV1(this IRiotGamesApi @base)
        {
            return new TftLeagueV1Endpoints(@base);
        }

        public static TftMatchV1Endpoints TftMatchV1(this IRiotGamesApi @base)
        {
            return new TftMatchV1Endpoints(@base);
        }

        public static TftSummonerV1Endpoints TftSummonerV1(this IRiotGamesApi @base)
        {
            return new TftSummonerV1Endpoints(@base);
        }

        public static ThirdPartyCodeV4Endpoints ThirdPartyCodeV4(this IRiotGamesApi @base)
        {
            return new ThirdPartyCodeV4Endpoints(@base);
        }

        public static TournamentStubV4Endpoints TournamentStubV4(this IRiotGamesApi @base)
        {
            return new TournamentStubV4Endpoints(@base);
        }

        public static TournamentV4Endpoints TournamentV4(this IRiotGamesApi @base)
        {
            return new TournamentV4Endpoints(@base);
        }

        public static ValContentV1Endpoints ValContentV1(this IRiotGamesApi @base)
        {
            return new ValContentV1Endpoints(@base);
        }

        public static ValMatchV1Endpoints ValMatchV1(this IRiotGamesApi @base)
        {
            return new ValMatchV1Endpoints(@base);
        }

    }
}

