
// This file is automatically generated.
// Do not directly edit.
// Generated on 2021-09-04T02:15:49.393Z

// Version 12e3bc69894adde9001edb3c64126cd90d4531bd

namespace Camille.RiotGames
{
    public static class RiotGamesExtensions
    {
        public static AccountV1Endpoints AccountV1(this IRiotGamesApi @base)
        {
            return new AccountV1Endpoints(@base);
        }

        public static ChampionMasteryV4Endpoints ChampionMasteryV4(this IRiotGamesApi @base)
        {
            return new ChampionMasteryV4Endpoints(@base);
        }

        public static ChampionV3Endpoints ChampionV3(this IRiotGamesApi @base)
        {
            return new ChampionV3Endpoints(@base);
        }

        public static ClashV1Endpoints ClashV1(this IRiotGamesApi @base)
        {
            return new ClashV1Endpoints(@base);
        }

        public static LeagueExpV4Endpoints LeagueExpV4(this IRiotGamesApi @base)
        {
            return new LeagueExpV4Endpoints(@base);
        }

        public static LeagueV4Endpoints LeagueV4(this IRiotGamesApi @base)
        {
            return new LeagueV4Endpoints(@base);
        }

        public static LolStatusV3Endpoints LolStatusV3(this IRiotGamesApi @base)
        {
            return new LolStatusV3Endpoints(@base);
        }

        public static LolStatusV4Endpoints LolStatusV4(this IRiotGamesApi @base)
        {
            return new LolStatusV4Endpoints(@base);
        }

        public static LorDeckV1Endpoints LorDeckV1(this IRiotGamesApi @base)
        {
            return new LorDeckV1Endpoints(@base);
        }

        public static LorInventoryV1Endpoints LorInventoryV1(this IRiotGamesApi @base)
        {
            return new LorInventoryV1Endpoints(@base);
        }

        public static LorMatchV1Endpoints LorMatchV1(this IRiotGamesApi @base)
        {
            return new LorMatchV1Endpoints(@base);
        }

        public static LorRankedV1Endpoints LorRankedV1(this IRiotGamesApi @base)
        {
            return new LorRankedV1Endpoints(@base);
        }

        public static LorStatusV1Endpoints LorStatusV1(this IRiotGamesApi @base)
        {
            return new LorStatusV1Endpoints(@base);
        }

        public static MatchV4Endpoints MatchV4(this IRiotGamesApi @base)
        {
            return new MatchV4Endpoints(@base);
        }

        public static MatchV5Endpoints MatchV5(this IRiotGamesApi @base)
        {
            return new MatchV5Endpoints(@base);
        }

        public static SpectatorV4Endpoints SpectatorV4(this IRiotGamesApi @base)
        {
            return new SpectatorV4Endpoints(@base);
        }

        public static SummonerV4Endpoints SummonerV4(this IRiotGamesApi @base)
        {
            return new SummonerV4Endpoints(@base);
        }

        public static TftLeagueV1Endpoints TftLeagueV1(this IRiotGamesApi @base)
        {
            return new TftLeagueV1Endpoints(@base);
        }

        public static TftMatchV1Endpoints TftMatchV1(this IRiotGamesApi @base)
        {
            return new TftMatchV1Endpoints(@base);
        }

        public static TftSummonerV1Endpoints TftSummonerV1(this IRiotGamesApi @base)
        {
            return new TftSummonerV1Endpoints(@base);
        }

        public static ThirdPartyCodeV4Endpoints ThirdPartyCodeV4(this IRiotGamesApi @base)
        {
            return new ThirdPartyCodeV4Endpoints(@base);
        }

        public static TournamentStubV4Endpoints TournamentStubV4(this IRiotGamesApi @base)
        {
            return new TournamentStubV4Endpoints(@base);
        }

        public static TournamentV4Endpoints TournamentV4(this IRiotGamesApi @base)
        {
            return new TournamentV4Endpoints(@base);
        }

        public static ValContentV1Endpoints ValContentV1(this IRiotGamesApi @base)
        {
            return new ValContentV1Endpoints(@base);
        }

        public static ValMatchV1Endpoints ValMatchV1(this IRiotGamesApi @base)
        {
            return new ValMatchV1Endpoints(@base);
        }

        public static ValRankedV1Endpoints ValRankedV1(this IRiotGamesApi @base)
        {
            return new ValRankedV1Endpoints(@base);
        }

        public static ValStatusV1Endpoints ValStatusV1(this IRiotGamesApi @base)
        {
            return new ValStatusV1Endpoints(@base);
        }

    }
}

