
// This file is automatically generated.
// Do not directly edit.
// Generated on 2022-09-01T03:55:42.556Z

// http://www.mingweisamuel.com/riotapi-schema/tool/
// Version 8a566197138131c2b213eb659d7dfb6de69bac17

namespace MingweiSamuel.Camille
{
#nullable disable
    public partial class RiotApi
    {
        public readonly AccountV1Endpoints AccountV1;
        public readonly ChampionMasteryV4Endpoints ChampionMasteryV4;
        public readonly ChampionV3Endpoints ChampionV3;
        public readonly ClashV1Endpoints ClashV1;
        public readonly LeagueExpV4Endpoints LeagueExpV4;
        public readonly LeagueV4Endpoints LeagueV4;
        public readonly LolChallengesV1Endpoints LolChallengesV1;
        public readonly LolStatusV3Endpoints LolStatusV3;
        public readonly LolStatusV4Endpoints LolStatusV4;
        public readonly LorDeckV1Endpoints LorDeckV1;
        public readonly LorInventoryV1Endpoints LorInventoryV1;
        public readonly LorMatchV1Endpoints LorMatchV1;
        public readonly LorRankedV1Endpoints LorRankedV1;
        public readonly LorStatusV1Endpoints LorStatusV1;
        public readonly MatchV5Endpoints MatchV5;
        public readonly SpectatorV4Endpoints SpectatorV4;
        public readonly SummonerV4Endpoints SummonerV4;
        public readonly TftLeagueV1Endpoints TftLeagueV1;
        public readonly TftMatchV1Endpoints TftMatchV1;
        public readonly TftSummonerV1Endpoints TftSummonerV1;
        public readonly TournamentStubV4Endpoints TournamentStubV4;
        public readonly TournamentV4Endpoints TournamentV4;
        public readonly ValContentV1Endpoints ValContentV1;
        public readonly ValMatchV1Endpoints ValMatchV1;
        public readonly ValRankedV1Endpoints ValRankedV1;
        public readonly ValStatusV1Endpoints ValStatusV1;

        private RiotApi()
        {
            AccountV1 = new AccountV1Endpoints(this);
            ChampionMasteryV4 = new ChampionMasteryV4Endpoints(this);
            ChampionV3 = new ChampionV3Endpoints(this);
            ClashV1 = new ClashV1Endpoints(this);
            LeagueExpV4 = new LeagueExpV4Endpoints(this);
            LeagueV4 = new LeagueV4Endpoints(this);
            LolChallengesV1 = new LolChallengesV1Endpoints(this);
            LolStatusV3 = new LolStatusV3Endpoints(this);
            LolStatusV4 = new LolStatusV4Endpoints(this);
            LorDeckV1 = new LorDeckV1Endpoints(this);
            LorInventoryV1 = new LorInventoryV1Endpoints(this);
            LorMatchV1 = new LorMatchV1Endpoints(this);
            LorRankedV1 = new LorRankedV1Endpoints(this);
            LorStatusV1 = new LorStatusV1Endpoints(this);
            MatchV5 = new MatchV5Endpoints(this);
            SpectatorV4 = new SpectatorV4Endpoints(this);
            SummonerV4 = new SummonerV4Endpoints(this);
            TftLeagueV1 = new TftLeagueV1Endpoints(this);
            TftMatchV1 = new TftMatchV1Endpoints(this);
            TftSummonerV1 = new TftSummonerV1Endpoints(this);
            TournamentStubV4 = new TournamentStubV4Endpoints(this);
            TournamentV4 = new TournamentV4Endpoints(this);
            ValContentV1 = new ValContentV1Endpoints(this);
            ValMatchV1 = new ValMatchV1Endpoints(this);
            ValRankedV1 = new ValRankedV1Endpoints(this);
            ValStatusV1 = new ValStatusV1Endpoints(this);
        }
    }
#nullable restore
}
